"""empty message

Revision ID: 50e347dc7f54
Revises: 519806a560f2
Create Date: 2023-07-03 15:15:11.118737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50e347dc7f54'
down_revision = '519806a560f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.String(length=10), nullable=True))
        batch_op.drop_column('nama')
        batch_op.drop_column('jabatan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jabatan', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('nama', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
